//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices.WS_OmnitracsCC_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", ConfigurationName="WS_OmnitracsCC_Service.IVehicleActivityWebService")]
    public interface IVehicleActivityWebService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse getGeofenceVisits(ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse> getGeofenceVisitsAsync(ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ReCServices.WS_OmnitracsCC_Service.getPositionsResponse getPositions(ReCServices.WS_OmnitracsCC_Service.getPositions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getPositionsResponse> getPositionsAsync(ReCServices.WS_OmnitracsCC_Service.getPositions request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ReCServices.WS_OmnitracsCC_Service.getAlertsResponse getAlerts(ReCServices.WS_OmnitracsCC_Service.getAlerts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getAlertsResponse> getAlertsAsync(ReCServices.WS_OmnitracsCC_Service.getAlerts request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityRequestDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientCodeField;
        
        private string endDateField;
        
        private string passwordField;
        
        private string startDateField;
        
        private string userNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientCode {
            get {
                return this.clientCodeField;
            }
            set {
                this.clientCodeField = value;
                this.RaisePropertyChanged("clientCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class alertCustomerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string alertTypeField;
        
        private string dateField;
        
        private long idalertField;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private string locationField;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private float odometerField;
        
        private bool odometerFieldSpecified;
        
        private string relevantInfoField;
        
        private float speedField;
        
        private bool speedFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alertType {
            get {
                return this.alertTypeField;
            }
            set {
                this.alertTypeField = value;
                this.RaisePropertyChanged("alertType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idalert {
            get {
                return this.idalertField;
            }
            set {
                this.idalertField = value;
                this.RaisePropertyChanged("idalert");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("latitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("longitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("odometer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odometerSpecified {
            get {
                return this.odometerFieldSpecified;
            }
            set {
                this.odometerFieldSpecified = value;
                this.RaisePropertyChanged("odometerSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string relevantInfo {
            get {
                return this.relevantInfoField;
            }
            set {
                this.relevantInfoField = value;
                this.RaisePropertyChanged("relevantInfo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("speed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool speedSpecified {
            get {
                return this.speedFieldSpecified;
            }
            set {
                this.speedFieldSpecified = value;
                this.RaisePropertyChanged("speedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityAlertDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alertCustomerDTO[] alertsField;
        
        private string aliasField;
        
        private int idUnitField;
        
        private bool idUnitFieldSpecified;
        
        private string serialnumberField;
        
        private string unitModelField;
        
        private string unitPlateField;
        
        private string vehicleTypeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("alerts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public alertCustomerDTO[] alerts {
            get {
                return this.alertsField;
            }
            set {
                this.alertsField = value;
                this.RaisePropertyChanged("alerts");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUnit {
            get {
                return this.idUnitField;
            }
            set {
                this.idUnitField = value;
                this.RaisePropertyChanged("idUnit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUnitSpecified {
            get {
                return this.idUnitFieldSpecified;
            }
            set {
                this.idUnitFieldSpecified = value;
                this.RaisePropertyChanged("idUnitSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serialnumber {
            get {
                return this.serialnumberField;
            }
            set {
                this.serialnumberField = value;
                this.RaisePropertyChanged("serialnumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unitModel {
            get {
                return this.unitModelField;
            }
            set {
                this.unitModelField = value;
                this.RaisePropertyChanged("unitModel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string unitPlate {
            get {
                return this.unitPlateField;
            }
            set {
                this.unitPlateField = value;
                this.RaisePropertyChanged("unitPlate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
                this.RaisePropertyChanged("vehicleType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class positionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string dateField;
        
        private string deviceModelField;
        
        private string deviceSerialField;
        
        private string directionField;
        
        private string georeferenceField;
        
        private string hdopField;
        
        private long idEventField;
        
        private bool idEventFieldSpecified;
        
        private bool ignitionOnField;
        
        private bool ignitionOnFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private string locationField;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string odometerField;
        
        private System.DateTime posTSField;
        
        private bool posTSFieldSpecified;
        
        private string productTypeField;
        
        private string reasonField;
        
        private System.DateTime receiveDateField;
        
        private bool receiveDateFieldSpecified;
        
        private string satellitesField;
        
        private string speedField;
        
        private string stateField;
        
        private string statusField;
        
        private string switchesField;
        
        private string unitStatusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deviceModel {
            get {
                return this.deviceModelField;
            }
            set {
                this.deviceModelField = value;
                this.RaisePropertyChanged("deviceModel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string deviceSerial {
            get {
                return this.deviceSerialField;
            }
            set {
                this.deviceSerialField = value;
                this.RaisePropertyChanged("deviceSerial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string georeference {
            get {
                return this.georeferenceField;
            }
            set {
                this.georeferenceField = value;
                this.RaisePropertyChanged("georeference");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string hdop {
            get {
                return this.hdopField;
            }
            set {
                this.hdopField = value;
                this.RaisePropertyChanged("hdop");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long idEvent {
            get {
                return this.idEventField;
            }
            set {
                this.idEventField = value;
                this.RaisePropertyChanged("idEvent");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEventSpecified {
            get {
                return this.idEventFieldSpecified;
            }
            set {
                this.idEventFieldSpecified = value;
                this.RaisePropertyChanged("idEventSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool ignitionOn {
            get {
                return this.ignitionOnField;
            }
            set {
                this.ignitionOnField = value;
                this.RaisePropertyChanged("ignitionOn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ignitionOnSpecified {
            get {
                return this.ignitionOnFieldSpecified;
            }
            set {
                this.ignitionOnFieldSpecified = value;
                this.RaisePropertyChanged("ignitionOnSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("latitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("longitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("odometer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime posTS {
            get {
                return this.posTSField;
            }
            set {
                this.posTSField = value;
                this.RaisePropertyChanged("posTS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool posTSSpecified {
            get {
                return this.posTSFieldSpecified;
            }
            set {
                this.posTSFieldSpecified = value;
                this.RaisePropertyChanged("posTSSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("productType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receiveDateSpecified {
            get {
                return this.receiveDateFieldSpecified;
            }
            set {
                this.receiveDateFieldSpecified = value;
                this.RaisePropertyChanged("receiveDateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string satellites {
            get {
                return this.satellitesField;
            }
            set {
                this.satellitesField = value;
                this.RaisePropertyChanged("satellites");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("speed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string switches {
            get {
                return this.switchesField;
            }
            set {
                this.switchesField = value;
                this.RaisePropertyChanged("switches");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string unitStatus {
            get {
                return this.unitStatusField;
            }
            set {
                this.unitStatusField = value;
                this.RaisePropertyChanged("unitStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class georeferenceDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private string geoReferenceCategoryField;
        
        private string geofenceVisitDateField;
        
        private string visitActionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string geoReferenceCategory {
            get {
                return this.geoReferenceCategoryField;
            }
            set {
                this.geoReferenceCategoryField = value;
                this.RaisePropertyChanged("geoReferenceCategory");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string geofenceVisitDate {
            get {
                return this.geofenceVisitDateField;
            }
            set {
                this.geofenceVisitDateField = value;
                this.RaisePropertyChanged("geofenceVisitDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string visitAction {
            get {
                return this.visitActionField;
            }
            set {
                this.visitActionField = value;
                this.RaisePropertyChanged("visitAction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vehicleActivityAlertResponseDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vehicleActivityPositionResponseDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(listVehicleActivityPositionResponseDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vehicleActivityGeoReferenceDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vehicleActivityGeoreferenceResponseDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class responseDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int responseCodeField;
        
        private bool responseCodeFieldSpecified;
        
        private string responseDescriptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseCodeSpecified {
            get {
                return this.responseCodeFieldSpecified;
            }
            set {
                this.responseCodeFieldSpecified = value;
                this.RaisePropertyChanged("responseCodeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityAlertResponseDTO : responseDTO {
        
        private vehicleActivityAlertDTO[] alertsActivityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("alertsActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public vehicleActivityAlertDTO[] alertsActivity {
            get {
                return this.alertsActivityField;
            }
            set {
                this.alertsActivityField = value;
                this.RaisePropertyChanged("alertsActivity");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityPositionResponseDTO : responseDTO {
        
        private string aliasField;
        
        private string aliasShipperField;
        
        private string clientCodeField;
        
        private int idUnitField;
        
        private bool idUnitFieldSpecified;
        
        private positionDTO[] positionsField;
        
        private string unitModelField;
        
        private string unitPlateField;
        
        private string vehicleTypeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string aliasShipper {
            get {
                return this.aliasShipperField;
            }
            set {
                this.aliasShipperField = value;
                this.RaisePropertyChanged("aliasShipper");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clientCode {
            get {
                return this.clientCodeField;
            }
            set {
                this.clientCodeField = value;
                this.RaisePropertyChanged("clientCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idUnit {
            get {
                return this.idUnitField;
            }
            set {
                this.idUnitField = value;
                this.RaisePropertyChanged("idUnit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUnitSpecified {
            get {
                return this.idUnitFieldSpecified;
            }
            set {
                this.idUnitFieldSpecified = value;
                this.RaisePropertyChanged("idUnitSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("positions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public positionDTO[] positions {
            get {
                return this.positionsField;
            }
            set {
                this.positionsField = value;
                this.RaisePropertyChanged("positions");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string unitModel {
            get {
                return this.unitModelField;
            }
            set {
                this.unitModelField = value;
                this.RaisePropertyChanged("unitModel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unitPlate {
            get {
                return this.unitPlateField;
            }
            set {
                this.unitPlateField = value;
                this.RaisePropertyChanged("unitPlate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
                this.RaisePropertyChanged("vehicleType");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class listVehicleActivityPositionResponseDTO : responseDTO {
        
        private vehicleActivityPositionResponseDTO[] vehiclesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("vehicles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public vehicleActivityPositionResponseDTO[] vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
                this.RaisePropertyChanged("vehicles");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityGeoReferenceDTO : responseDTO {
        
        private string aliasField;
        
        private georeferenceDTO[] geofencesField;
        
        private int idUnitField;
        
        private bool idUnitFieldSpecified;
        
        private string unitModelField;
        
        private string unitPlateField;
        
        private string vehicleTypeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("geofences", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public georeferenceDTO[] geofences {
            get {
                return this.geofencesField;
            }
            set {
                this.geofencesField = value;
                this.RaisePropertyChanged("geofences");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUnit {
            get {
                return this.idUnitField;
            }
            set {
                this.idUnitField = value;
                this.RaisePropertyChanged("idUnit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUnitSpecified {
            get {
                return this.idUnitFieldSpecified;
            }
            set {
                this.idUnitFieldSpecified = value;
                this.RaisePropertyChanged("idUnitSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unitModel {
            get {
                return this.unitModelField;
            }
            set {
                this.unitModelField = value;
                this.RaisePropertyChanged("unitModel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unitPlate {
            get {
                return this.unitPlateField;
            }
            set {
                this.unitPlateField = value;
                this.RaisePropertyChanged("unitPlate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
                this.RaisePropertyChanged("vehicleType");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/")]
    public partial class vehicleActivityGeoreferenceResponseDTO : responseDTO {
        
        private vehicleActivityGeoReferenceDTO[] geoActivityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("geoActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public vehicleActivityGeoReferenceDTO[] geoActivity {
            get {
                return this.geoActivityField;
            }
            set {
                this.geoActivityField = value;
                this.RaisePropertyChanged("geoActivity");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGeofenceVisits", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getGeofenceVisits {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request;
        
        public getGeofenceVisits() {
        }
        
        public getGeofenceVisits(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGeofenceVisitsResponse", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getGeofenceVisitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityGeoreferenceResponseDTO @return;
        
        public getGeofenceVisitsResponse() {
        }
        
        public getGeofenceVisitsResponse(ReCServices.WS_OmnitracsCC_Service.vehicleActivityGeoreferenceResponseDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPositions", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getPositions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request;
        
        public getPositions() {
        }
        
        public getPositions(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPositionsResponse", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getPositionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.listVehicleActivityPositionResponseDTO @return;
        
        public getPositionsResponse() {
        }
        
        public getPositionsResponse(ReCServices.WS_OmnitracsCC_Service.listVehicleActivityPositionResponseDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlerts", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getAlerts {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request;
        
        public getAlerts() {
        }
        
        public getAlerts(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlertsResponse", WrapperNamespace="http://sei.rest.services.client.maya.omnitracs.mx/", IsWrapped=true)]
    public partial class getAlertsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sei.rest.services.client.maya.omnitracs.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityAlertResponseDTO @return;
        
        public getAlertsResponse() {
        }
        
        public getAlertsResponse(ReCServices.WS_OmnitracsCC_Service.vehicleActivityAlertResponseDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleActivityWebServiceChannel : ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleActivityWebServiceClient : System.ServiceModel.ClientBase<ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService>, ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService {
        
        public VehicleActivityWebServiceClient() {
        }
        
        public VehicleActivityWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleActivityWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleActivityWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleActivityWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getGeofenceVisits(ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits request) {
            return base.Channel.getGeofenceVisits(request);
        }
        
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityGeoreferenceResponseDTO getGeofenceVisits(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits inValue = new ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits();
            inValue.request = request;
            ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse retVal = ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getGeofenceVisits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse> ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getGeofenceVisitsAsync(ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits request) {
            return base.Channel.getGeofenceVisitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getGeofenceVisitsResponse> getGeofenceVisitsAsync(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits inValue = new ReCServices.WS_OmnitracsCC_Service.getGeofenceVisits();
            inValue.request = request;
            return ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getGeofenceVisitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsCC_Service.getPositionsResponse ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getPositions(ReCServices.WS_OmnitracsCC_Service.getPositions request) {
            return base.Channel.getPositions(request);
        }
        
        public ReCServices.WS_OmnitracsCC_Service.listVehicleActivityPositionResponseDTO getPositions(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getPositions inValue = new ReCServices.WS_OmnitracsCC_Service.getPositions();
            inValue.request = request;
            ReCServices.WS_OmnitracsCC_Service.getPositionsResponse retVal = ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getPositions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getPositionsResponse> ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getPositionsAsync(ReCServices.WS_OmnitracsCC_Service.getPositions request) {
            return base.Channel.getPositionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getPositionsResponse> getPositionsAsync(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getPositions inValue = new ReCServices.WS_OmnitracsCC_Service.getPositions();
            inValue.request = request;
            return ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getPositionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsCC_Service.getAlertsResponse ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getAlerts(ReCServices.WS_OmnitracsCC_Service.getAlerts request) {
            return base.Channel.getAlerts(request);
        }
        
        public ReCServices.WS_OmnitracsCC_Service.vehicleActivityAlertResponseDTO getAlerts(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getAlerts inValue = new ReCServices.WS_OmnitracsCC_Service.getAlerts();
            inValue.request = request;
            ReCServices.WS_OmnitracsCC_Service.getAlertsResponse retVal = ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getAlerts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getAlertsResponse> ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService.getAlertsAsync(ReCServices.WS_OmnitracsCC_Service.getAlerts request) {
            return base.Channel.getAlertsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsCC_Service.getAlertsResponse> getAlertsAsync(ReCServices.WS_OmnitracsCC_Service.vehicleActivityRequestDTO request) {
            ReCServices.WS_OmnitracsCC_Service.getAlerts inValue = new ReCServices.WS_OmnitracsCC_Service.getAlerts();
            inValue.request = request;
            return ((ReCServices.WS_OmnitracsCC_Service.IVehicleActivityWebService)(this)).getAlertsAsync(inValue);
        }
    }
}
