//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices.WS_SGIT_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Localizacion", ConfigurationName="WS_SGIT_Service.LocalizacionPort")]
    public interface LocalizacionPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Localizacion#acceso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string acceso(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Localizacion#acceso", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<string> accesoAsync(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Localizacion#posicion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="arreglo")]
        string posicion(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Localizacion#posicion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="arreglo")]
        System.Threading.Tasks.Task<string> posicionAsync(string usuario, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalizacionPortChannel : ReCServices.WS_SGIT_Service.LocalizacionPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalizacionPortClient : System.ServiceModel.ClientBase<ReCServices.WS_SGIT_Service.LocalizacionPort>, ReCServices.WS_SGIT_Service.LocalizacionPort {
        
        public LocalizacionPortClient() {
        }
        
        public LocalizacionPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalizacionPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string acceso(string usuario, string contrasena) {
            return base.Channel.acceso(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> accesoAsync(string usuario, string contrasena) {
            return base.Channel.accesoAsync(usuario, contrasena);
        }
        
        public string posicion(string usuario, string contrasena) {
            return base.Channel.posicion(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> posicionAsync(string usuario, string contrasena) {
            return base.Channel.posicionAsync(usuario, contrasena);
        }
    }
}
