//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices.WS_SEND_EventService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://astus.com/service/event/2010/11", ConfigurationName="WS_SEND_EventService.EventContract")]
    public interface EventContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetTripEventResponse")]
        ReCServices.WS_SEND_EventService.GetTripEventResponse GetTripEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripEvent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetTripEventResponse")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetTripEventResponse> GetTripEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripAccessoryEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetAccessoryEventResponse")]
        ReCServices.WS_SEND_EventService.GetAccessoryEventResponse GetTripAccessoryEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripAccessoryEvent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetAccessoryEventResponse")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetAccessoryEventResponse> GetTripAccessoryEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripPositionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetPositionEventResponse")]
        ReCServices.WS_SEND_EventService.GetPositionEventResponse GetTripPositionEvent(ReCServices.WS_SEND_EventService.GetTripPositionEventRequest GetTripPositionEventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetTripPositionEvent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetPositionEventResponse")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetPositionEventResponse> GetTripPositionEventAsync(ReCServices.WS_SEND_EventService.GetTripPositionEventRequest GetTripPositionEventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetPositionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetPositionEventResponse")]
        ReCServices.WS_SEND_EventService.GetPositionEventResponse GetPositionEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetPositionEvent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetPositionEventResponse")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetPositionEventResponse> GetPositionEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetAccessoryEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetAccessoryEventResponse")]
        ReCServices.WS_SEND_EventService.GetAccessoryEventResponse GetAccessoryEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/event/2010/11/EventContract/GetAccessoryEvent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetAccessoryEventResponse")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetAccessoryEventResponse> GetAccessoryEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class EventRequest : AuthenticatedRequest {
        
        private System.DateTime startDateTimeField;
        
        private System.Nullable<System.DateTime> endDateTimeField;
        
        private int[] vehiclesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
                this.RaisePropertyChanged("StartDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
                this.RaisePropertyChanged("EndDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public int[] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
                this.RaisePropertyChanged("Vehicles");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTripPositionEventRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class AuthenticatedRequest : MessageBase {
        
        private Token unsafeTokenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Token UnsafeToken {
            get {
                return this.unsafeTokenField;
            }
            set {
                this.unsafeTokenField = value;
                this.RaisePropertyChanged("UnsafeToken");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class Token : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class AccessoryEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int accessoryIDField;
        
        private int vehicleIDField;
        
        private System.DateTime eventDateTimeField;
        
        private System.Nullable<int> tripEventIDField;
        
        private System.Nullable<double> tripEventDistanceField;
        
        private double odometerField;
        
        private AccessoryState accessoryStateField;
        
        private System.Nullable<double> latitudeField;
        
        private System.Nullable<double> longitudeField;
        
        private System.Nullable<double> valueField;
        
        private string textValueField;
        
        private string choiceTextField;
        
        private System.Nullable<short> choiceValueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AccessoryID {
            get {
                return this.accessoryIDField;
            }
            set {
                this.accessoryIDField = value;
                this.RaisePropertyChanged("AccessoryID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
                this.RaisePropertyChanged("EventDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> TripEventID {
            get {
                return this.tripEventIDField;
            }
            set {
                this.tripEventIDField = value;
                this.RaisePropertyChanged("TripEventID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<double> TripEventDistance {
            get {
                return this.tripEventDistanceField;
            }
            set {
                this.tripEventDistanceField = value;
                this.RaisePropertyChanged("TripEventDistance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("Odometer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public AccessoryState AccessoryState {
            get {
                return this.accessoryStateField;
            }
            set {
                this.accessoryStateField = value;
                this.RaisePropertyChanged("AccessoryState");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<double> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<double> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<double> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string TextValue {
            get {
                return this.textValueField;
            }
            set {
                this.textValueField = value;
                this.RaisePropertyChanged("TextValue");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string ChoiceText {
            get {
                return this.choiceTextField;
            }
            set {
                this.choiceTextField = value;
                this.RaisePropertyChanged("ChoiceText");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<short> ChoiceValue {
            get {
                return this.choiceValueField;
            }
            set {
                this.choiceValueField = value;
                this.RaisePropertyChanged("ChoiceValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public enum AccessoryState {
        
        /// <comentarios/>
        Low,
        
        /// <comentarios/>
        High,
        
        /// <comentarios/>
        Normal,
        
        /// <comentarios/>
        Ponctuel,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/services/event/2010/11")]
    public partial class PositionEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int vehicleIDField;
        
        private System.Nullable<int> tripEventIDField;
        
        private System.Nullable<double> distanceField;
        
        private System.DateTime gPSDateTimeField;
        
        private short headingField;
        
        private byte speedField;
        
        private bool isGPSValidField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.Nullable<int> timeSpanField;
        
        private VehicleState vehicleStateField;
        
        private bool isOverSpeedField;
        
        private bool vehicleNameField;
        
        private string closestLocationField;
        
        private System.Nullable<int> employeeIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> TripEventID {
            get {
                return this.tripEventIDField;
            }
            set {
                this.tripEventIDField = value;
                this.RaisePropertyChanged("TripEventID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<double> Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime GPSDateTime {
            get {
                return this.gPSDateTimeField;
            }
            set {
                this.gPSDateTimeField = value;
                this.RaisePropertyChanged("GPSDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
                this.RaisePropertyChanged("Heading");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsGPSValid {
            get {
                return this.isGPSValidField;
            }
            set {
                this.isGPSValidField = value;
                this.RaisePropertyChanged("IsGPSValid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> TimeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("TimeSpan");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VehicleState VehicleState {
            get {
                return this.vehicleStateField;
            }
            set {
                this.vehicleStateField = value;
                this.RaisePropertyChanged("VehicleState");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsOverSpeed {
            get {
                return this.isOverSpeedField;
            }
            set {
                this.isOverSpeedField = value;
                this.RaisePropertyChanged("IsOverSpeed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool VehicleName {
            get {
                return this.vehicleNameField;
            }
            set {
                this.vehicleNameField = value;
                this.RaisePropertyChanged("VehicleName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ClosestLocation {
            get {
                return this.closestLocationField;
            }
            set {
                this.closestLocationField = value;
                this.RaisePropertyChanged("ClosestLocation");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public enum VehicleState {
        
        /// <comentarios/>
        Moving,
        
        /// <comentarios/>
        Disarmed,
        
        /// <comentarios/>
        Armed,
        
        /// <comentarios/>
        Idle,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class TripEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int vehicleIDField;
        
        private int employeeIDField;
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime endDateTimeField;
        
        private int driveTimeField;
        
        private float distanceField;
        
        private int totalIdleTimeField;
        
        private int endTripIdleTimeField;
        
        private int stopTimeField;
        
        private int maxSpeedField;
        
        private int maxRpmField;
        
        private float endTripOdometerField;
        
        private float endTripMotorTimeField;
        
        private int overRpmTimeField;
        
        private int overSpeedTimeField;
        
        private int overAccTimeField;
        
        private int overDecTimeField;
        
        private PositionEvent startPositionEventField;
        
        private PositionEvent endPositionEventField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
                this.RaisePropertyChanged("StartDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
                this.RaisePropertyChanged("EndDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int DriveTime {
            get {
                return this.driveTimeField;
            }
            set {
                this.driveTimeField = value;
                this.RaisePropertyChanged("DriveTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TotalIdleTime {
            get {
                return this.totalIdleTimeField;
            }
            set {
                this.totalIdleTimeField = value;
                this.RaisePropertyChanged("TotalIdleTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int EndTripIdleTime {
            get {
                return this.endTripIdleTimeField;
            }
            set {
                this.endTripIdleTimeField = value;
                this.RaisePropertyChanged("EndTripIdleTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int StopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
                this.RaisePropertyChanged("StopTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int MaxSpeed {
            get {
                return this.maxSpeedField;
            }
            set {
                this.maxSpeedField = value;
                this.RaisePropertyChanged("MaxSpeed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MaxRpm {
            get {
                return this.maxRpmField;
            }
            set {
                this.maxRpmField = value;
                this.RaisePropertyChanged("MaxRpm");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public float EndTripOdometer {
            get {
                return this.endTripOdometerField;
            }
            set {
                this.endTripOdometerField = value;
                this.RaisePropertyChanged("EndTripOdometer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public float EndTripMotorTime {
            get {
                return this.endTripMotorTimeField;
            }
            set {
                this.endTripMotorTimeField = value;
                this.RaisePropertyChanged("EndTripMotorTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int OverRpmTime {
            get {
                return this.overRpmTimeField;
            }
            set {
                this.overRpmTimeField = value;
                this.RaisePropertyChanged("OverRpmTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int OverSpeedTime {
            get {
                return this.overSpeedTimeField;
            }
            set {
                this.overSpeedTimeField = value;
                this.RaisePropertyChanged("OverSpeedTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int OverAccTime {
            get {
                return this.overAccTimeField;
            }
            set {
                this.overAccTimeField = value;
                this.RaisePropertyChanged("OverAccTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int OverDecTime {
            get {
                return this.overDecTimeField;
            }
            set {
                this.overDecTimeField = value;
                this.RaisePropertyChanged("OverDecTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public PositionEvent StartPositionEvent {
            get {
                return this.startPositionEventField;
            }
            set {
                this.startPositionEventField = value;
                this.RaisePropertyChanged("StartPositionEvent");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public PositionEvent EndPositionEvent {
            get {
                return this.endPositionEventField;
            }
            set {
                this.endPositionEventField = value;
                this.RaisePropertyChanged("EndPositionEvent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticatedRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTripPositionEventRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetPositionEventResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAccessoryEventResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTripEventResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public abstract partial class MessageBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetPositionEventResponse : MessageBase {
        
        private PositionEvent[] positionEventsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public PositionEvent[] PositionEvents {
            get {
                return this.positionEventsField;
            }
            set {
                this.positionEventsField = value;
                this.RaisePropertyChanged("PositionEvents");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetAccessoryEventResponse : MessageBase {
        
        private AccessoryEvent[] accessoryEventsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public AccessoryEvent[] AccessoryEvents {
            get {
                return this.accessoryEventsField;
            }
            set {
                this.accessoryEventsField = value;
                this.RaisePropertyChanged("AccessoryEvents");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetTripEventResponse : MessageBase {
        
        private TripEvent[] tripEventsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public TripEvent[] TripEvents {
            get {
                return this.tripEventsField;
            }
            set {
                this.tripEventsField = value;
                this.RaisePropertyChanged("TripEvents");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetTripPositionEventRequest : AuthenticatedRequest {
        
        private int tripEventIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TripEventID {
            get {
                return this.tripEventIDField;
            }
            set {
                this.tripEventIDField = value;
                this.RaisePropertyChanged("TripEventID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventContractChannel : ReCServices.WS_SEND_EventService.EventContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventContractClient : System.ServiceModel.ClientBase<ReCServices.WS_SEND_EventService.EventContract>, ReCServices.WS_SEND_EventService.EventContract {
        
        public EventContractClient() {
        }
        
        public EventContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReCServices.WS_SEND_EventService.GetTripEventResponse GetTripEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetTripEvent(EventRequest);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetTripEventResponse> GetTripEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetTripEventAsync(EventRequest);
        }
        
        public ReCServices.WS_SEND_EventService.GetAccessoryEventResponse GetTripAccessoryEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetTripAccessoryEvent(EventRequest);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetAccessoryEventResponse> GetTripAccessoryEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetTripAccessoryEventAsync(EventRequest);
        }
        
        public ReCServices.WS_SEND_EventService.GetPositionEventResponse GetTripPositionEvent(ReCServices.WS_SEND_EventService.GetTripPositionEventRequest GetTripPositionEventRequest) {
            return base.Channel.GetTripPositionEvent(GetTripPositionEventRequest);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetPositionEventResponse> GetTripPositionEventAsync(ReCServices.WS_SEND_EventService.GetTripPositionEventRequest GetTripPositionEventRequest) {
            return base.Channel.GetTripPositionEventAsync(GetTripPositionEventRequest);
        }
        
        public ReCServices.WS_SEND_EventService.GetPositionEventResponse GetPositionEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetPositionEvent(EventRequest);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetPositionEventResponse> GetPositionEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetPositionEventAsync(EventRequest);
        }
        
        public ReCServices.WS_SEND_EventService.GetAccessoryEventResponse GetAccessoryEvent(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetAccessoryEvent(EventRequest);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_EventService.GetAccessoryEventResponse> GetAccessoryEventAsync(ReCServices.WS_SEND_EventService.EventRequest EventRequest) {
            return base.Channel.GetAccessoryEventAsync(EventRequest);
        }
    }
}
