//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices.WS_OmnitracsMasetto_Service {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exception.sharedws")]
    public partial class WSException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.otswebws")]
    public partial class TransactionBlock : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private byte[] transactionsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("transactions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websvcs.otswebws", ConfigurationName="WS_OmnitracsMasetto_Service.OTSWebSvcs")]
    public interface OTSWebSvcs {
        
        // CODEGEN: El parámetro 'dequeueReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReCServices.WS_OmnitracsMasetto_Service.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="dequeueReturn")]
        ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse dequeue(ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse> dequeueAsync(ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest request);
        
        // CODEGEN: El parámetro 'getSubscriberInfoReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReCServices.WS_OmnitracsMasetto_Service.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSubscriberInfoReturn")]
        ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse getSubscriberInfo(ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse> getSubscriberInfoAsync(ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest request);
        
        // CODEGEN: El parámetro 'dequeue2Return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReCServices.WS_OmnitracsMasetto_Service.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="dequeue2Return")]
        ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response dequeue2(ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response> dequeue2Async(ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dequeue", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class dequeueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int subscriberId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int blockCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int transactionId;
        
        public dequeueRequest() {
        }
        
        public dequeueRequest(int subscriberId, int blockCount, int transactionId) {
            this.subscriberId = subscriberId;
            this.blockCount = blockCount;
            this.transactionId = transactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dequeueResponse", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class dequeueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock dequeueReturn;
        
        public dequeueResponse() {
        }
        
        public dequeueResponse(ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock dequeueReturn) {
            this.dequeueReturn = dequeueReturn;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.otswebws")]
    public partial class SubscriberInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool enqueueEnabledField;
        
        private int enqueueCountField;
        
        private string enqueueCountResetTimeField;
        
        private string enqueueEnabledTimeField;
        
        private int fullThresholdField;
        
        private string lastDequeueTimeField;
        
        private string lastEnqueueTimeField;
        
        private int dequeueBlockCountField;
        
        private int queueDepthField;
        
        private int warnThresholdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool enqueueEnabled {
            get {
                return this.enqueueEnabledField;
            }
            set {
                this.enqueueEnabledField = value;
                this.RaisePropertyChanged("enqueueEnabled");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int enqueueCount {
            get {
                return this.enqueueCountField;
            }
            set {
                this.enqueueCountField = value;
                this.RaisePropertyChanged("enqueueCount");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string enqueueCountResetTime {
            get {
                return this.enqueueCountResetTimeField;
            }
            set {
                this.enqueueCountResetTimeField = value;
                this.RaisePropertyChanged("enqueueCountResetTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string enqueueEnabledTime {
            get {
                return this.enqueueEnabledTimeField;
            }
            set {
                this.enqueueEnabledTimeField = value;
                this.RaisePropertyChanged("enqueueEnabledTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int fullThreshold {
            get {
                return this.fullThresholdField;
            }
            set {
                this.fullThresholdField = value;
                this.RaisePropertyChanged("fullThreshold");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string lastDequeueTime {
            get {
                return this.lastDequeueTimeField;
            }
            set {
                this.lastDequeueTimeField = value;
                this.RaisePropertyChanged("lastDequeueTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string lastEnqueueTime {
            get {
                return this.lastEnqueueTimeField;
            }
            set {
                this.lastEnqueueTimeField = value;
                this.RaisePropertyChanged("lastEnqueueTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int dequeueBlockCount {
            get {
                return this.dequeueBlockCountField;
            }
            set {
                this.dequeueBlockCountField = value;
                this.RaisePropertyChanged("dequeueBlockCount");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int queueDepth {
            get {
                return this.queueDepthField;
            }
            set {
                this.queueDepthField = value;
                this.RaisePropertyChanged("queueDepth");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int warnThreshold {
            get {
                return this.warnThresholdField;
            }
            set {
                this.warnThresholdField = value;
                this.RaisePropertyChanged("warnThreshold");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscriberInfo", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class getSubscriberInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int subscriberID;
        
        public getSubscriberInfoRequest() {
        }
        
        public getSubscriberInfoRequest(int subscriberID) {
            this.subscriberID = subscriberID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscriberInfoResponse", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class getSubscriberInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ReCServices.WS_OmnitracsMasetto_Service.SubscriberInfo getSubscriberInfoReturn;
        
        public getSubscriberInfoResponse() {
        }
        
        public getSubscriberInfoResponse(ReCServices.WS_OmnitracsMasetto_Service.SubscriberInfo getSubscriberInfoReturn) {
            this.getSubscriberInfoReturn = getSubscriberInfoReturn;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.otswebws")]
    public partial class TransactionBlock2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private byte[] transactionsField;
        
        private long transactionIdOutField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("transactions");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long transactionIdOut {
            get {
                return this.transactionIdOutField;
            }
            set {
                this.transactionIdOutField = value;
                this.RaisePropertyChanged("transactionIdOut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dequeue2", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class dequeue2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int subscriberId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transactionIdIn;
        
        public dequeue2Request() {
        }
        
        public dequeue2Request(int subscriberId, long transactionIdIn) {
            this.subscriberId = subscriberId;
            this.transactionIdIn = transactionIdIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dequeue2Response", WrapperNamespace="http://websvcs.otswebws", IsWrapped=true)]
    public partial class dequeue2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.otswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock2 dequeue2Return;
        
        public dequeue2Response() {
        }
        
        public dequeue2Response(ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock2 dequeue2Return) {
            this.dequeue2Return = dequeue2Return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OTSWebSvcsChannel : ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OTSWebSvcsClient : System.ServiceModel.ClientBase<ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs>, ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs {
        
        public OTSWebSvcsClient() {
        }
        
        public OTSWebSvcsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OTSWebSvcsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTSWebSvcsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTSWebSvcsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.dequeue(ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest request) {
            return base.Channel.dequeue(request);
        }
        
        public ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock dequeue(int subscriberId, int blockCount, int transactionId) {
            ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest inValue = new ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest();
            inValue.subscriberId = subscriberId;
            inValue.blockCount = blockCount;
            inValue.transactionId = transactionId;
            ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse retVal = ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).dequeue(inValue);
            return retVal.dequeueReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse> ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.dequeueAsync(ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest request) {
            return base.Channel.dequeueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeueResponse> dequeueAsync(int subscriberId, int blockCount, int transactionId) {
            ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest inValue = new ReCServices.WS_OmnitracsMasetto_Service.dequeueRequest();
            inValue.subscriberId = subscriberId;
            inValue.blockCount = blockCount;
            inValue.transactionId = transactionId;
            return ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).dequeueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.getSubscriberInfo(ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest request) {
            return base.Channel.getSubscriberInfo(request);
        }
        
        public ReCServices.WS_OmnitracsMasetto_Service.SubscriberInfo getSubscriberInfo(int subscriberID) {
            ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest inValue = new ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest();
            inValue.subscriberID = subscriberID;
            ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse retVal = ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).getSubscriberInfo(inValue);
            return retVal.getSubscriberInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse> ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.getSubscriberInfoAsync(ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest request) {
            return base.Channel.getSubscriberInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoResponse> getSubscriberInfoAsync(int subscriberID) {
            ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest inValue = new ReCServices.WS_OmnitracsMasetto_Service.getSubscriberInfoRequest();
            inValue.subscriberID = subscriberID;
            return ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).getSubscriberInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.dequeue2(ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request request) {
            return base.Channel.dequeue2(request);
        }
        
        public ReCServices.WS_OmnitracsMasetto_Service.TransactionBlock2 dequeue2(int subscriberId, long transactionIdIn) {
            ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request inValue = new ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request();
            inValue.subscriberId = subscriberId;
            inValue.transactionIdIn = transactionIdIn;
            ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response retVal = ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).dequeue2(inValue);
            return retVal.dequeue2Return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response> ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs.dequeue2Async(ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request request) {
            return base.Channel.dequeue2Async(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_OmnitracsMasetto_Service.dequeue2Response> dequeue2Async(int subscriberId, long transactionIdIn) {
            ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request inValue = new ReCServices.WS_OmnitracsMasetto_Service.dequeue2Request();
            inValue.subscriberId = subscriberId;
            inValue.transactionIdIn = transactionIdIn;
            return ((ReCServices.WS_OmnitracsMasetto_Service.OTSWebSvcs)(this)).dequeue2Async(inValue);
        }
    }
}
