//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices.WS_SEND_GetLastPosition {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://astus.com/service/state/2010/11", ConfigurationName="WS_SEND_GetLastPosition.StateContract")]
    public interface StateContract {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://astus.com/service/event/2010/11) no coincide con el valor predeterminado (http://astus.com/service/state/2010/11).
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/state/2010/11/StateContract/GetCurrentVehiclePosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetPositionEventResponse")]
        ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse GetLastPositionEvent(ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/state/2010/11/StateContract/GetCurrentVehiclePosition", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse> GetLastPositionEventAsync(ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://astus.com/service/event/2010/11) no coincide con el valor predeterminado (http://astus.com/service/state/2010/11).
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/state/2010/11/StateContract/GetCurrentVehicleState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetStateResponse")]
        ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse GetLastState(ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/state/2010/11/StateContract/GetCurrentVehicleState", ReplyAction="*")]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse> GetLastStateAsync(ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/state/2010/11")]
    public partial class StateRequest : AuthenticatedRequest {
        
        private int[] vehiclesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public int[] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
                this.RaisePropertyChanged("Vehicles");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class AuthenticatedRequest : MessageBase {
        
        private Token unsafeTokenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Token UnsafeToken {
            get {
                return this.unsafeTokenField;
            }
            set {
                this.unsafeTokenField = value;
                this.RaisePropertyChanged("UnsafeToken");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class Token : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/services/event/2010/11")]
    public partial class LastStateEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int vehicleIDField;
        
        private System.Nullable<int> tripEventIDField;
        
        private System.Nullable<double> distanceField;
        
        private System.DateTime gPSDateTimeField;
        
        private short headingField;
        
        private byte speedField;
        
        private bool isGPSValidField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.Nullable<int> timeSpanField;
        
        private VehicleState vehicleStateField;
        
        private bool isOverSpeedField;
        
        private string deviceTypeField;
        
        private System.Nullable<System.DateTime> lastConnectionDateField;
        
        private double odometerField;
        
        private double motorHourField;
        
        private int employeeIDField;
        
        private int vehicleAvailabilityStateIDField;
        
        private string vehicleAvailabilityStateNameField;
        
        private int vehicleCustomStateIDField;
        
        private string vehicleCustomStateNameField;
        
        private int[] stateRuleGroupIDsField;
        
        private string[] stateRuleGroupNamesField;
        
        private string[] accessoryNameListField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> TripEventID {
            get {
                return this.tripEventIDField;
            }
            set {
                this.tripEventIDField = value;
                this.RaisePropertyChanged("TripEventID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<double> Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime GPSDateTime {
            get {
                return this.gPSDateTimeField;
            }
            set {
                this.gPSDateTimeField = value;
                this.RaisePropertyChanged("GPSDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
                this.RaisePropertyChanged("Heading");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsGPSValid {
            get {
                return this.isGPSValidField;
            }
            set {
                this.isGPSValidField = value;
                this.RaisePropertyChanged("IsGPSValid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> TimeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("TimeSpan");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VehicleState VehicleState {
            get {
                return this.vehicleStateField;
            }
            set {
                this.vehicleStateField = value;
                this.RaisePropertyChanged("VehicleState");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsOverSpeed {
            get {
                return this.isOverSpeedField;
            }
            set {
                this.isOverSpeedField = value;
                this.RaisePropertyChanged("IsOverSpeed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("DeviceType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LastConnectionDate {
            get {
                return this.lastConnectionDateField;
            }
            set {
                this.lastConnectionDateField = value;
                this.RaisePropertyChanged("LastConnectionDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("Odometer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double MotorHour {
            get {
                return this.motorHourField;
            }
            set {
                this.motorHourField = value;
                this.RaisePropertyChanged("MotorHour");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int VehicleAvailabilityStateID {
            get {
                return this.vehicleAvailabilityStateIDField;
            }
            set {
                this.vehicleAvailabilityStateIDField = value;
                this.RaisePropertyChanged("VehicleAvailabilityStateID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string VehicleAvailabilityStateName {
            get {
                return this.vehicleAvailabilityStateNameField;
            }
            set {
                this.vehicleAvailabilityStateNameField = value;
                this.RaisePropertyChanged("VehicleAvailabilityStateName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int VehicleCustomStateID {
            get {
                return this.vehicleCustomStateIDField;
            }
            set {
                this.vehicleCustomStateIDField = value;
                this.RaisePropertyChanged("VehicleCustomStateID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string VehicleCustomStateName {
            get {
                return this.vehicleCustomStateNameField;
            }
            set {
                this.vehicleCustomStateNameField = value;
                this.RaisePropertyChanged("VehicleCustomStateName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public int[] StateRuleGroupIDs {
            get {
                return this.stateRuleGroupIDsField;
            }
            set {
                this.stateRuleGroupIDsField = value;
                this.RaisePropertyChanged("StateRuleGroupIDs");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        public string[] StateRuleGroupNames {
            get {
                return this.stateRuleGroupNamesField;
            }
            set {
                this.stateRuleGroupNamesField = value;
                this.RaisePropertyChanged("StateRuleGroupNames");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=23)]
        public string[] AccessoryNameList {
            get {
                return this.accessoryNameListField;
            }
            set {
                this.accessoryNameListField = value;
                this.RaisePropertyChanged("AccessoryNameList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public enum VehicleState {
        
        /// <comentarios/>
        Moving,
        
        /// <comentarios/>
        Disarmed,
        
        /// <comentarios/>
        Armed,
        
        /// <comentarios/>
        Idle,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/services/event/2010/11")]
    public partial class PositionEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int vehicleIDField;
        
        private System.Nullable<int> tripEventIDField;
        
        private System.Nullable<double> distanceField;
        
        private System.DateTime gPSDateTimeField;
        
        private short headingField;
        
        private byte speedField;
        
        private bool isGPSValidField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.Nullable<int> timeSpanField;
        
        private VehicleState vehicleStateField;
        
        private bool isOverSpeedField;
        
        private bool vehicleNameField;
        
        private string closestLocationField;
        
        private System.Nullable<int> employeeIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> TripEventID {
            get {
                return this.tripEventIDField;
            }
            set {
                this.tripEventIDField = value;
                this.RaisePropertyChanged("TripEventID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<double> Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime GPSDateTime {
            get {
                return this.gPSDateTimeField;
            }
            set {
                this.gPSDateTimeField = value;
                this.RaisePropertyChanged("GPSDateTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
                this.RaisePropertyChanged("Heading");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsGPSValid {
            get {
                return this.isGPSValidField;
            }
            set {
                this.isGPSValidField = value;
                this.RaisePropertyChanged("IsGPSValid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> TimeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("TimeSpan");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VehicleState VehicleState {
            get {
                return this.vehicleStateField;
            }
            set {
                this.vehicleStateField = value;
                this.RaisePropertyChanged("VehicleState");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsOverSpeed {
            get {
                return this.isOverSpeedField;
            }
            set {
                this.isOverSpeedField = value;
                this.RaisePropertyChanged("IsOverSpeed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool VehicleName {
            get {
                return this.vehicleNameField;
            }
            set {
                this.vehicleNameField = value;
                this.RaisePropertyChanged("VehicleName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ClosestLocation {
            get {
                return this.closestLocationField;
            }
            set {
                this.closestLocationField = value;
                this.RaisePropertyChanged("ClosestLocation");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStateResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetPositionEventResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticatedRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public abstract partial class MessageBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetStateResponse : MessageBase {
        
        private LastStateEvent[] lastStateEventField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public LastStateEvent[] LastStateEvent {
            get {
                return this.lastStateEventField;
            }
            set {
                this.lastStateEventField = value;
                this.RaisePropertyChanged("LastStateEvent");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/event/2010/11")]
    public partial class GetPositionEventResponse : MessageBase {
        
        private PositionEvent[] positionEventsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public PositionEvent[] PositionEvents {
            get {
                return this.positionEventsField;
            }
            set {
                this.positionEventsField = value;
                this.RaisePropertyChanged("PositionEvents");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPositionEvent", WrapperNamespace="http://astus.com/service/state/2010/11", IsWrapped=true)]
    public partial class GetLastPositionEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/state/2010/11", Order=0)]
        public ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest;
        
        public GetLastPositionEventRequest() {
        }
        
        public GetLastPositionEventRequest(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            this.StateRequest = StateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastPositionEventResponse", WrapperNamespace="http://astus.com/service/state/2010/11", IsWrapped=true)]
    public partial class GetLastPositionEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/event/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/event/2010/11")]
        public ReCServices.WS_SEND_GetLastPosition.GetPositionEventResponse GetPositionEventResponse;
        
        public GetLastPositionEventResponse() {
        }
        
        public GetLastPositionEventResponse(ReCServices.WS_SEND_GetLastPosition.GetPositionEventResponse GetPositionEventResponse) {
            this.GetPositionEventResponse = GetPositionEventResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastState", WrapperNamespace="http://astus.com/service/state/2010/11", IsWrapped=true)]
    public partial class GetLastStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/state/2010/11", Order=0)]
        public ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest;
        
        public GetLastStateRequest() {
        }
        
        public GetLastStateRequest(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            this.StateRequest = StateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastStateResponse", WrapperNamespace="http://astus.com/service/state/2010/11", IsWrapped=true)]
    public partial class GetLastStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/event/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/event/2010/11")]
        public ReCServices.WS_SEND_GetLastPosition.GetStateResponse GetStateResponse;
        
        public GetLastStateResponse() {
        }
        
        public GetLastStateResponse(ReCServices.WS_SEND_GetLastPosition.GetStateResponse GetStateResponse) {
            this.GetStateResponse = GetStateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StateContractChannel : ReCServices.WS_SEND_GetLastPosition.StateContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StateContractClient : System.ServiceModel.ClientBase<ReCServices.WS_SEND_GetLastPosition.StateContract>, ReCServices.WS_SEND_GetLastPosition.StateContract {
        
        public StateContractClient() {
        }
        
        public StateContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StateContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StateContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse ReCServices.WS_SEND_GetLastPosition.StateContract.GetLastPositionEvent(ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest request) {
            return base.Channel.GetLastPositionEvent(request);
        }
        
        public ReCServices.WS_SEND_GetLastPosition.GetPositionEventResponse GetLastPositionEvent(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest inValue = new ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest();
            inValue.StateRequest = StateRequest;
            ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse retVal = ((ReCServices.WS_SEND_GetLastPosition.StateContract)(this)).GetLastPositionEvent(inValue);
            return retVal.GetPositionEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse> ReCServices.WS_SEND_GetLastPosition.StateContract.GetLastPositionEventAsync(ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest request) {
            return base.Channel.GetLastPositionEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventResponse> GetLastPositionEventAsync(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest inValue = new ReCServices.WS_SEND_GetLastPosition.GetLastPositionEventRequest();
            inValue.StateRequest = StateRequest;
            return ((ReCServices.WS_SEND_GetLastPosition.StateContract)(this)).GetLastPositionEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse ReCServices.WS_SEND_GetLastPosition.StateContract.GetLastState(ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest request) {
            return base.Channel.GetLastState(request);
        }
        
        public ReCServices.WS_SEND_GetLastPosition.GetStateResponse GetLastState(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest inValue = new ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest();
            inValue.StateRequest = StateRequest;
            ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse retVal = ((ReCServices.WS_SEND_GetLastPosition.StateContract)(this)).GetLastState(inValue);
            return retVal.GetStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse> ReCServices.WS_SEND_GetLastPosition.StateContract.GetLastStateAsync(ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest request) {
            return base.Channel.GetLastStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReCServices.WS_SEND_GetLastPosition.GetLastStateResponse> GetLastStateAsync(ReCServices.WS_SEND_GetLastPosition.StateRequest StateRequest) {
            ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest inValue = new ReCServices.WS_SEND_GetLastPosition.GetLastStateRequest();
            inValue.StateRequest = StateRequest;
            return ((ReCServices.WS_SEND_GetLastPosition.StateContract)(this)).GetLastStateAsync(inValue);
        }
    }
}
