//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Monitoreo : DbContext
    {
        public Monitoreo()
            : base("name=Monitoreo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Color_Consulta_Result> Color_Consulta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Color_Consulta_Result>("Color_Consulta");
        }
    
        public virtual ObjectResult<MonitoreoAutomatico_CargaSiguienteViaje_Result> MonitoreoAutomatico_CargaSiguienteViaje(Nullable<int> idUsuario, string iMEI)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var iMEIParameter = iMEI != null ?
                new ObjectParameter("IMEI", iMEI) :
                new ObjectParameter("IMEI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonitoreoAutomatico_CargaSiguienteViaje_Result>("MonitoreoAutomatico_CargaSiguienteViaje", idUsuarioParameter, iMEIParameter);
        }
    
        public virtual ObjectResult<NotificacionIncidencia_CargaHTML_Result> NotificacionIncidencia_CargaHTML(string iMEI, string usuario, string incidencia)
        {
            var iMEIParameter = iMEI != null ?
                new ObjectParameter("IMEI", iMEI) :
                new ObjectParameter("IMEI", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var incidenciaParameter = incidencia != null ?
                new ObjectParameter("Incidencia", incidencia) :
                new ObjectParameter("Incidencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificacionIncidencia_CargaHTML_Result>("NotificacionIncidencia_CargaHTML", iMEIParameter, usuarioParameter, incidenciaParameter);
        }
    }
}
